Use BookStoreVT
INSERT INTO YayinEvi(YayinEviAd, YayinEviAdres)
VALUES 
('KARPA YAYINCILIK', 'ÝSTANBUL / Türkiye'),
('YAPI KREDÝ YAYINLARI', 'AnNKARA / Türkiye'),
('CAN YAYINLARI' , 'BURSA / Türkiye'),
('TUDEM YAYINEVÝ' , 'ANKARA / Türkiye'),
('TÝMAÞ ÇOCUK YAYINLARI' , 'MANÝSA / Türkiye'),
('TÜBÝTAK YAYINLARI' , 'BURSA / Türkiye'),
('DOÐAN YAYINLARI' , 'BURSA / Türkiye'),
('KRONÝK KÝTAP' , 'BURDUR / Türkiye'),
('TÝMAÞ YAYINLARI' , 'BOLU / Türkiye'),
('PEGASUS YAYINLARI' , 'ÝSTANBUL / Türkiye'),
('GÜNIÞIÐI KÝTAPLIÐI' , 'BALIKESÝR / Türkiye'),
('METÝS YAYINLARI' , 'ÝSTANBUL / Türkiye'),
('ÝLETÝÞÝM YAYINLARI' , 'MARAÞ / Türkiye'),
('ALTIN KÝTAPLAR' , 'ELAZIÐ / Türkiye'),
('TÝMAÞ GENÇ' , 'BOLU / Türkiye'),
('CAN ÇOCUK YAYINLARI' , 'BURSA / Türkiye'),
('KETEBE YAYINEVÝ' , 'MANÝSA / Türkiye'),
('KIRMIZI KEDÝ YAYINEVÝ' , 'KOCAELÝ / Türkiye'),
('ÝTHAKÝ YAYINLARI' , 'ÝSTANBUL / Türkiye'),
('HAYY KÝTAP' , 'ÝSTANBUL / Türkiye'),
('TÜRKÝYE ÝÞ BANKASI KÜLTÜR YAYINLARI' , 'SÝVAS / Türkiye'),
('AÝLE YAYINLARI' , 'BALIKESÝR / Türkiye'),
('DERGAH YAYINLARI' , 'ÝSTANBUL / Türkiye'),
('DOMÝNGO YAYINEVÝ' , 'MANÝSA / Türkiye'),
('TÝMAÞ ÝLK GENÇ' , 'BALIKESÝR / Türkiye'),
('ALFA YAYINLARI' , 'BURSA / Türkiye'),
('CEZVE ÇOCUK' , 'BOLU / Türkiye'),
('NESÝL YAYINLARI' , 'MARAÞ / Türkiye'),
('EVEREST YAYINLARI' , 'ADANA / Türkiye'),
('ÝNKILAP KÝTAPEVÝ' , 'ÝSTANBUL / Türkiye'),
('SEL YAYINCILIK' , 'ÝSTANBUL / Türkiye'),
('UÐURBÖCEÐÝ YAYINLARI' , 'BURSA / Türkiye'),
('REMZÝ KÝTAPEVÝ' , 'BALIKESÝR / Türkiye'),
('AYRINTI YAYINLARI' , 'ADANA / Türkiye'),
('ÝNSAN YAYINLARI' , 'ADANA / Türkiye'),
('DOÐAN EGMONT ÇOCUK KÝTAPLARI' , 'ÝSTANBUL / Türkiye'),
('YEDÝÝKLÝM YAYINLARI' , 'ÝSTANBUL / Türkiye'),
('SÝA KÝTAP' , 'BALIKESÝR / Türkiye'),
('HEY KÝTAP' , 'ADANA / Türkiye'),
('DOMÝNGO ÇOCUK' , 'ÝSTANBUL / Türkiye'),
('SAY YAYINLARI' , 'ELAZIÐ / Türkiye'),
('FOM KÝTAP' , 'MARAÞ / Türkiye'),
('DÝYOJEN YAYINCILIK' , 'BURSA / Türkiye'),
('EPÝLSON YAYINEVÝ' , 'BALIKESÝR / Türkiye'),
('DOÐAN ÇOCUK' , 'BOLU / Türkiye'),
('POZÝTÝF YAYINLARI' , 'BURSA / Türkiye'),
('BENÝM HOCAM YAYINLARI' , 'ADANA / Türkiye'),
('PEGEM AKADEMÝ YAYINCILIK' , 'ANKARA / Türkiye')