use BookStoreVT
insert into KitapTurleri values 
    ('Roman'),
    ('Þiir'),
    ('Deneme'),
    ('Tarihi Roman'),
    ('Makale'),
    ('Biyografi'),
    ('Týp'),
    ('Felsefe'),
    ('Korku'),
    ('Bilim Kurgu'),
    ('Polisiye'),
    ('Fantastik'),
    ('Tarih'),
    ('Psikoloji'),
    ('Klasik Edebiyat'),
    ('Kurgusal Olmayan'),
    ('Drama'),
    ('Çocuk Kitabý'),
    ('Gezi'),
    ('Edebiyat Eleþtirisi'),
    ('Politika'),
    ('Aþk Romaný'),
    ('Bilim'),
    ('Sanat'),
    ('Sosyoloji'),
    ('Türk Edebiyatý'),
    ('Dünya Edebiyatý'),
    ('Bilim Tarihi'),
    ('Kýsa Hikaye'),
    ('Doða Kitabý'),
    ('Mizah'),
    ('Mitoloji'),
    ('Moda'),
    ('Felsefi Roman'),
    ('Klasik Roman'),
    ('Yemek Kitabý'),
    ('Yabancý Dil Öðretimi'),
    ('Felsefe'),
    ('Mühendislik'),
    ('Antoloji')
