use BookStoreVT
INSERT INTO Yazarlar (YazarAd, YazarSoyad)
VALUES
	('George', 'Orwell'),
    ('Jane', 'Austen'),
    ('Mark', 'Twain'),
    ('J.K.', 'Rowling'),
    ('Leo', 'Tolstoy'),
    ('Agatha', 'Christie'),
    ('William', 'Shakespeare'),
    ('Charles', 'Dickens'),
    ('Ernest', 'Hemingway'),
    ('J.R.R.', 'Tolkien'),
    ('Fyodor', 'Dostoevsky'),
    ('Gabriel', 'García Márquez'),
    ('Harper', 'Lee'),
    ('Stephen', 'King'),
    ('Virginia', 'Woolf'),
    ('H.G.', 'Wells'),
    ('Aldous', 'Huxley'),
    ('Ray', 'Bradbury'),
    ('Hermann', 'Hesse'),
    ('George', 'Eliot'),
    ('Ayn', 'Rand'),
    ('Kurt', 'Vonnegut'),
    ('Sait Faik', 'Abasýyanýk'),
    ('Isaac', 'Asimov'),
    ('Dante', 'Alighieri'),
    ('Jane', 'Austen'),
    ('H.P.', 'Lovecraft'),
	('Ahmet', 'Ümit'),
	('Orhan', 'Pamuk'),
	('William', 'Golding'),
	('Sabahattin', 'Ali'),
	('Peyami', 'Safa'),
	('Franz', 'Kafka'),
	('Stefan', 'Zweig'),
	('Paulo',  'Coelho'),
	('Johanna',  'Spyri'),
	('Carlo' , 'Collodi'),
	('Stieg' ,'Larsson')


